name: Compile Plugin

# The workflow will run on every push and pull request to the repository
on:
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
  pull_request:
    branches: ["main"]
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  compile-plugin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout BZFlag
      run: git clone -b 2.4 https://github.com/BZFlag-Dev/bzflag.git bzflag
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: ./bzflag/plugins/ircRelay
    - name: Prepare Packages
      run: sudo apt-get update; sudo apt-get install -y build-essential automake autoconf libtool libc-ares-dev libcurl3-dev libglew-dev libncurses-dev libsdl2-dev zlib1g-dev; sudo apt-get clean
    - name: Build BZFlag Plugin
      run: cd bzflag; ./autogen.sh; ./configure --disable-client --disable-bzadmin --enable-custom-plugins=ircRelay; make -j$(nproc --ignore=1); sudo make install-strip
    - name: Archive BZFS Plugins
      uses: actions/upload-artifact@v4
      with:
        name: ircRelay
        path: /usr/local/lib/bzflag/ircRelay.*
